### ISSUE TITLE
Simple way to enable extension in postgres? The README is confusing me

### ISSUE THREAD

**Issue by corneliusroemer** [kaspermarstal/plprql#75]
How do I enable the plprql extension in postgres? Do I really need to run all these commands listed in the readme, installing all sorts of packages in ubuntu?

How can I add it to the standard docker image of postgres?

**Comment by kaspermarstal** [comment]
You can create a new docker image based on the standard docker image that installs one of the .deb packages from the release page. That would be the easiest way.

**Comment by kaspermarstal** [comment]
I improved the README and added a [docker/plprql.Dockerfile](https://github.com/kaspermarstal/plprql/blob/main/docker/plprql.Dockerfile) that you can use as inspiration.

**Comment by Vonng** [comment]
I have built RPM and DED packages for [plprql](https://pigsty.cc/docs/pgext/lang/plprql/) and provided repositories for [yum](https://github.com/pgsty/pkg?tab=readme-ov-file#yum-repo) (EL8/EL9) and [apt](https://github.com/pgsty/pkg?tab=readme-ov-file#apt-repo) (Debian 12 / Ubuntu 22.04).

> How do I enable the plprql extension in postgres? Do I really need to run all these commands listed in the readme, installing all sorts of packages in ubuntu?
> 
> How can I add it to the standard docker image of postgres?
